# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 97473482-9903-57e7-af24-d921448662e7

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sampleappaoaichatgpt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4cc0f77bba124a008e494bfb8d7081ed }}
        password: ${{ secrets.AzureAppService_ContainerPassword_02c99141e7c24acfb7a876640f0425ae }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4cc0f77bba124a008e494bfb8d7081ed }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '97473482-9903-57e7-af24-d921448662e7'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b42064226c25433ab4bc541a38f05532 }}
        images: 'sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4cc0f77bba124a008e494bfb8d7081ed }}/sample-app-aoai-chatgpt:${{ github.sha }}'